export const RUBROS = [
  "Alimentos y bebidas",
  "Moda y textil",
  "Tecnología",
  "Turismo",
  "Artesanías y diseño",
  "Salud y bienestar",
  "Educación",
  "Servicios profesionales",
  "Agro y producción",
  "Comercio",
  "Otros",
] as const;

export const DEPARTAMENTOS = [
  "Artigas",
  "Canelones",
  "Cerro Largo",
  "Colonia",
  "Durazno",
  "Flores",
  "Florida",
  "Lavalleja",
  "Maldonado",
  "Montevideo",
  "Paysandú",
  "Río Negro",
  "Rivera",
  "Rocha",
  "Salto",
  "San José",
  "Soriano",
  "Tacuarembó",
  "Treinta y Tres",
] as const;
